# Generated by Django 5.1.4 on 2024-12-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransaction',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
