# Generated by Django 5.1.3 on 2025-01-09 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_staff',
            new_name='in_staff',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='is_superuser',
            new_name='in_superuser',
        ),
    ]
