# Generated by Django 5.1.3 on 2025-01-09 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_is_staff_profile_in_staff_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='in_staff',
            new_name='in_superusers',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='in_superuser',
            new_name='is_staff',
        ),
    ]
