# Generated by Django 5.1.3 on 2025-01-09 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_in_staff_profile_in_superusers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_staff',
            new_name='in_staff',
        ),
    ]
